export interface LearningResourceSeed {
  id: number;
  title: string;
  source: 'iGOT' | 'NSSTA';
  competency: string;
  secondary_competencies: string[];
  target_roles: string[];
  relevant_departments: string[];
  relevant_assignments: string[];
  min_recommended_score: number;
  difficulty_level: 'Beginner' | 'Intermediate' | 'Advanced';
  prerequisites: string[];
  estimated_duration: string;
  learning_type: 'Course' | 'Training Programme';
  description: string;
  expected_outcome: string;
}

export const SEED_LEARNING_RESOURCES: LearningResourceSeed[] = [
  // =========================================================================
  // 1. OFFICIAL STATISTICS (Existing 12 courses: IDs 1..12)
  // =========================================================================
  {
    id: 1,
    title: 'Official Statistics Foundations',
    source: 'iGOT',
    competency: 'Statistics',
    secondary_competencies: ['Methodology & Theory', 'Sampling', 'Data Quality'],
    target_roles: ['Statistical Officer', 'Junior Statistical Officer', 'Field Operations Officer'],
    relevant_departments: ['Survey Division', 'Survey Division (NSSO)', 'Field Operations Division', 'Economic Statistics Division'],
    relevant_assignments: ['PLFS Microdata Validation', 'Survey Data Analysis', 'Periodic Labour Force Survey (PLFS) Microdata Validation', 'Consumer Price Index Scrutiny'],
    min_recommended_score: 0,
    difficulty_level: 'Beginner',
    prerequisites: [],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Foundations of India official statistical infrastructure, MoSPI administrative mandates, multi-stage stratified sampling principles, and national survey methodologies.',
    expected_outcome: 'Formulate valid sampling frames, comprehend PSU selection protocols, and audit survey responses against national standards.'
  },
  {
    id: 2,
    title: 'Python for Data Analysis in Government',
    source: 'iGOT',
    competency: 'Python',
    secondary_competencies: ['Data Analysis', 'Data Quality', 'Automation'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Data Processing Assistant'],
    relevant_departments: ['Survey Division', 'Survey Division (NSSO)', 'National Accounts Division', 'Economic Statistics Division'],
    relevant_assignments: ['Periodic Labour Force Survey (PLFS) Microdata Validation', 'PLFS Microdata Validation', 'Survey Data Analysis', 'Price Statistics / CPI', 'Data Architecture'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Basic Computing Logic', 'Basic Python Training (iGOT Karmayogi)'],
    estimated_duration: '5 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Practical data manipulation using Python, Pandas, and NumPy for national survey microdata processing, automated data pipelines, and error screening.',
    expected_outcome: 'Build automated Python validation scripts for raw survey schedules, execute vector operations, and screen outliers.'
  },
  {
    id: 3,
    title: 'Machine Learning for Public Policy',
    source: 'iGOT',
    competency: 'Data Analysis',
    secondary_competencies: ['Python', 'Statistics', 'AI for Statistics'],
    target_roles: ['Assistant Director', 'Deputy Director', 'Statistical Officer'],
    relevant_departments: ['Data Storage & Dissemination Division', 'Economic Statistics Division', 'National Accounts Division'],
    relevant_assignments: ['Survey Data Analysis', 'Big Data Analytics', 'High-Frequency Indicators'],
    min_recommended_score: 50,
    difficulty_level: 'Advanced',
    prerequisites: ['Python for Data Analysis', 'Applied Data Analysis'],
    estimated_duration: '6 weeks (hybrid)',
    learning_type: 'Course',
    description: 'Foundational concepts of machine learning, classification, clustering, and predictive modeling for public administration and national statistical infrastructure.',
    expected_outcome: 'Evaluate ML algorithms for anomaly detection in economic registers and understand AI safety/ethical guidelines in governance.'
  },
  {
    id: 4,
    title: 'Statistical Data Management',
    source: 'iGOT',
    competency: 'Data Analysis',
    secondary_competencies: ['Statistics', 'Data Quality', 'Relational Databases'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Data Processing Assistant'],
    relevant_departments: ['Survey Division', 'Field Operations Division', 'Economic Statistics Division'],
    relevant_assignments: ['Survey Data Analysis', 'Database Scrutiny', 'Data Architecture', 'Quality Audits'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Official Statistics Foundations'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Database design principles, relational querying, audit trails, and data governance frameworks for national statistical repositories.',
    expected_outcome: 'Implement multi-stage data consistency validation rules and manage relational datasets across survey rounds.'
  },
  {
    id: 5,
    title: 'R Programming for Statistical Analysis',
    source: 'iGOT',
    competency: 'Python',
    secondary_competencies: ['Statistics', 'Data Analysis', 'Econometrics'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Assistant Director'],
    relevant_departments: ['National Accounts Division', 'Price Statistics Division', 'Survey Division'],
    relevant_assignments: ['Time Series Analysis', 'Econometric Modeling', 'Survey Data Analysis', 'GSDP Compilation'],
    min_recommended_score: 35,
    difficulty_level: 'Intermediate',
    prerequisites: ['Descriptive Statistics', 'Basic Computing Logic'],
    estimated_duration: '5 weeks (online)',
    learning_type: 'Course',
    description: 'Computational statistical workflows in R using Tidyverse, sampling weight adjustments, survey estimation libraries, and reproducible R Markdown reporting.',
    expected_outcome: 'Build automated estimation scripts applying sample multipliers and calculating complex survey standard errors.'
  },
  {
    id: 6,
    title: 'Survey Methodology and Sampling',
    source: 'NSSTA',
    competency: 'Statistics',
    secondary_competencies: ['Methodology & Theory', 'Data Analysis', 'Sampling Design'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Assistant Director', 'Field Operations Officer'],
    relevant_departments: ['Survey Division (NSSO)', 'Survey Division', 'Field Operations Division'],
    relevant_assignments: ['Survey Data Analysis', 'Sampling Frame Preparation', 'PLFS Microdata Validation', 'Field Investigation'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Probability Theory & Basic Inference'],
    estimated_duration: '2 weeks residential (NSSTA Greater Noida)',
    learning_type: 'Training Programme',
    description: 'Rigorous institutional training on multi-stage stratified sampling designs, circular systematic sampling, sampling variance estimation, and non-sampling error control.',
    expected_outcome: 'Formulate sampling stratification protocols, determine optimal sample sizes, and evaluate design effects for socio-economic surveys.'
  },
  {
    id: 7,
    title: 'Official Statistics and Data Quality',
    source: 'NSSTA',
    competency: 'Statistics',
    secondary_competencies: ['Data Quality', 'Data Analysis', 'UN-FPOS Standards'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Assistant Director', 'Deputy Director'],
    relevant_departments: ['Survey Division', 'Economic Statistics Division', 'National Accounts Division'],
    relevant_assignments: ['Microdata Validation', 'Quality Assurance', 'Survey Oversight', 'Quality Audits'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['NSSTA Induction Training'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'National Quality Assurance Framework (NQAF), United Nations Fundamental Principles of Official Statistics, microdata editing, and item-nonresponse imputation.',
    expected_outcome: 'Design robust field scrutiny checklists and apply statistical imputation standards for survey microdata releases.'
  },
  {
    id: 8,
    title: 'GIS Applications in Official Statistics',
    source: 'NSSTA',
    competency: 'Data Visualization',
    secondary_competencies: ['Spatial Analysis', 'Field Operations', 'Thematic Cartography'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Assistant Director'],
    relevant_departments: ['Field Operations Division', 'Survey Division', 'Data Storage & Dissemination Division'],
    relevant_assignments: ['GIS / Spatial Data', 'Urban Frame Survey (UFS) Mapping', 'Geospatial Frame Preparation', 'Field Operations'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Data Visualization Basics'],
    estimated_duration: '3 weeks residential',
    learning_type: 'Training Programme',
    description: 'Geographic Information Systems (GIS), digital boundary demarcation, QGIS workflows, and geospatial sample frame preparation for national census and surveys.',
    expected_outcome: 'Construct geo-referenced sampling frames, generate choropleth district maps, and validate spatial boundary polygons.'
  },
  {
    id: 9,
    title: 'Statistical Computing with R',
    source: 'NSSTA',
    competency: 'Python',
    secondary_competencies: ['Data Analysis', 'Statistics', 'Simulation'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Assistant Director'],
    relevant_departments: ['National Accounts Division', 'Price Statistics Division', 'Survey Division'],
    relevant_assignments: ['Econometric Modeling', 'Survey Data Analysis', 'Index Computation', 'Macroeconomic Estimation'],
    min_recommended_score: 40,
    difficulty_level: 'Intermediate',
    prerequisites: ['Basic Statistics', 'NSSTA Induction'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Hands-on lab intensive on statistical programming, bootstrapping survey variances, Monte Carlo simulation, and microdata processing pipelines.',
    expected_outcome: 'Develop automated analysis scripts for national survey microdata releases with verified reproducible standards.'
  },
  {
    id: 10,
    title: 'AI Applications in Official Statistics',
    source: 'NSSTA',
    competency: 'AI for Statistics',
    secondary_competencies: ['Python', 'Machine Learning', 'Natural Language Processing'],
    target_roles: ['Assistant Director', 'Deputy Director', 'Senior Statistical Officer', 'Statistical Officer'],
    relevant_departments: ['Data Storage & Dissemination Division', 'National Accounts Division', 'Survey Division'],
    relevant_assignments: ['Big Data Analytics', 'Automated Industry Classification (NIC)', 'High-Frequency Indicators'],
    min_recommended_score: 60,
    difficulty_level: 'Advanced',
    prerequisites: ['Python for Data Analysis', 'Applied Data Analysis', 'Survey Methodology'],
    estimated_duration: '3 weeks intensive residential',
    learning_type: 'Training Programme',
    description: 'Cutting-edge machine learning and NLP for automated industrial code mapping (NIC/NCO), satellite imagery for agricultural estimation, and synthetic data generation.',
    expected_outcome: 'Deploy machine learning classifiers for trade and survey schedules, evaluating model auditability and algorithmic fairness.'
  },
  {
    id: 11,
    title: 'Consumer Price Index (CPI) Compilation & Price Statistics',
    source: 'NSSTA',
    competency: 'Data Analysis',
    secondary_competencies: ['Statistics', 'Price Indexation', 'Index Numbers'],
    target_roles: ['Statistical Officer', 'Senior Statistical Officer', 'Assistant Director'],
    relevant_departments: ['Price Statistics Division', 'Economic Statistics Division'],
    relevant_assignments: ['Price Statistics / CPI', 'Consumer Price Index Scrutiny', 'Inflation Analysis', 'Rural/Urban Price Collection'],
    min_recommended_score: 25,
    difficulty_level: 'Intermediate',
    prerequisites: ['Index Number Theory'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Laspeyres price indexing, geometric mean aggregation, elementary aggregates, web scraping for price quotes, and hedonic quality adjustments.',
    expected_outcome: 'Compute monthly headline and core inflation indices, impute missing quotations, and audit price relative consistency.'
  },
  {
    id: 12,
    title: 'National Accounts & Gross State Domestic Product (GSDP) Framework',
    source: 'NSSTA',
    competency: 'Data Analysis',
    secondary_competencies: ['Statistics', 'Macroeconomics', 'SNA 2008'],
    target_roles: ['Assistant Director', 'Deputy Director', 'Statistical Officer', 'Senior Statistical Officer'],
    relevant_departments: ['National Accounts Division', 'Economic Statistics Division'],
    relevant_assignments: ['National Accounts / GDP', 'GSDP Compilation & Sectoral Value Added', 'Gross State Domestic Product (GSDP) Compilation', 'Annual Survey of Industries (ASI) Estimation'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Macroeconomic Aggregates', 'Induction Program'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'System of National Accounts (SNA 2008), gross value added (GVA) estimation across primary/secondary/tertiary sectors, and state income accounts.',
    expected_outcome: 'Compile sector-wise GSDP estimates, apply deflators, and reconcile corporate financial data with statistical benchmarks.'
  },

  // =========================================================================
  // 2. ENGINEERING & PUBLIC WORKS (Civil Engineer: IDs 101..107)
  // =========================================================================
  {
    id: 101,
    title: 'Digital Project Monitoring & PM-GatiShakti GIS for Engineers',
    source: 'iGOT',
    competency: 'Digital Project Monitoring',
    secondary_competencies: ['Project Management', 'GIS / Spatial Planning', 'Drone Surveys'],
    target_roles: ['Civil Engineer', 'Assistant Engineer', 'Executive Engineer'],
    relevant_departments: ['Central Public Works Department (CPWD)', 'State Public Works Department (PWD)', 'National Highways Authority of India (NHAI)'],
    relevant_assignments: ['Urban Infrastructure & Roadways', 'Bridge & Highway Construction', 'Public Works Quality Monitoring'],
    min_recommended_score: 40,
    difficulty_level: 'Intermediate',
    prerequisites: ['Project Management Fundamentals'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Advanced digital project tracking using PM-GatiShakti National Master Plan GIS platform, drone-based milestone inspections, and mobile Geo-tagging for public infrastructure.',
    expected_outcome: 'Integrate linear infrastructure project milestones into PM-GatiShakti spatial layers and audit drone surveillance footage against physical billing schedules.'
  },
  {
    id: 102,
    title: 'Project Management for Government Infrastructure',
    source: 'iGOT',
    competency: 'Project Management',
    secondary_competencies: ['Quality Assurance', 'Cost Estimation', 'CPWD Works Manual'],
    target_roles: ['Civil Engineer', 'Assistant Engineer', 'Executive Engineer'],
    relevant_departments: ['Central Public Works Department (CPWD)', 'State Public Works Department (PWD)', 'NHAI', 'Irrigation & Water Resources Department'],
    relevant_assignments: ['Urban Infrastructure & Roadways', 'Bridge & Highway Construction', 'Government Building & Housing Projects'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Basic Civil Engineering'],
    estimated_duration: '5 weeks (hybrid)',
    learning_type: 'Course',
    description: 'Critical Path Method (CPM/PERT), milestone monitoring, contractor tracking, and delay mitigation protocols adhering to standard CPWD works procedures.',
    expected_outcome: 'Construct robust CPM schedules, compute activity float, mitigate project slippages, and manage contractor timeline compliances.'
  },
  {
    id: 103,
    title: 'Public Works Contract Management & Dispute Arbitration',
    source: 'iGOT',
    competency: 'Contract Management',
    secondary_competencies: ['Project Management', 'Legal Compliance', 'EPC Contracts'],
    target_roles: ['Civil Engineer', 'Executive Engineer', 'Assistant Engineer'],
    relevant_departments: ['State Public Works Department (PWD)', 'CPWD', 'NHAI'],
    relevant_assignments: ['Urban Infrastructure & Roadways', 'Bridge & Highway Construction', 'Public Works Quality Monitoring'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['CPWD Works Manual Overview'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'EPC and HAM contract clauses, time extensions, variation orders, liquidated damages computation, and alternative dispute arbitration in public works.',
    expected_outcome: 'Draft contractual notices, enforce liquidated damages thresholds, evaluate variation items, and prepare defense briefs for arbitration tribunals.'
  },
  {
    id: 104,
    title: 'Cost Estimation & Delhi Schedule of Rates (DSR/CPWD)',
    source: 'iGOT',
    competency: 'Cost Estimation',
    secondary_competencies: ['Project Management', 'CPWD Works Manual'],
    target_roles: ['Civil Engineer', 'Assistant Engineer'],
    relevant_departments: ['CPWD', 'State Public Works Department (PWD)', 'Municipal Engineering Department'],
    relevant_assignments: ['Urban Infrastructure & Roadways', 'Government Building & Housing Projects', 'Irrigation & Water Resource Management'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Civil Engineering Measurements'],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Practical preparation of Detailed Project Reports (DPR), application of Delhi Schedule of Rates (DSR), carriage lead-lift rate analysis, and administrative approval limits.',
    expected_outcome: 'Prepare item-wise abstract estimates, compute rate adjustments for quarry distances, and format DPRs for administrative sanction.'
  },
  {
    id: 105,
    title: 'Quality Assurance & Material Testing in Civil Construction',
    source: 'NSSTA',
    competency: 'Quality Assurance',
    secondary_competencies: ['Safety & Compliance', 'IS Codes', 'Material Testing'],
    target_roles: ['Civil Engineer', 'Assistant Engineer', 'Executive Engineer'],
    relevant_departments: ['CPWD', 'State Public Works Department (PWD)', 'NHAI'],
    relevant_assignments: ['Public Works Quality Monitoring', 'Bridge & Highway Construction', 'Urban Infrastructure & Roadways'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Concrete Technology & Soil Mechanics'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Hands-on laboratory testing for cement, concrete cube compressive strength (IS 456), bituminous mix design, non-destructive ultrasonic testing, and third-party QA audits.',
    expected_outcome: 'Verify field quality control registers, conduct slump and core tests, and reject sub-standard material consignments with statutory audit protection.'
  },
  {
    id: 106,
    title: 'Building Information Modeling (BIM) for Public Works',
    source: 'iGOT',
    competency: 'Building Information Modeling (BIM)',
    secondary_competencies: ['Project Management', 'Cost Estimation', '3D Modeling'],
    target_roles: ['Civil Engineer', 'Executive Engineer'],
    relevant_departments: ['CPWD', 'NHAI', 'Metro Rail Corporations'],
    relevant_assignments: ['Government Building & Housing Projects', 'Bridge & Highway Construction'],
    min_recommended_score: 50,
    difficulty_level: 'Advanced',
    prerequisites: ['Cost Estimation & DSR', 'Project Management'],
    estimated_duration: '6 weeks (online)',
    learning_type: 'Course',
    description: '3D digital twin modeling, clash detection between civil and MEP structures, and lifecycle asset management for large public infrastructure projects.',
    expected_outcome: 'Navigate 3D BIM models, identify inter-disciplinary spatial clashes prior to concrete pouring, and streamline contractor revision submissions.'
  },
  {
    id: 107,
    title: 'Safety Norms & Environmental Compliance in Public Works',
    source: 'iGOT',
    competency: 'Safety & Compliance',
    secondary_competencies: ['Quality Assurance', 'NBC Standards'],
    target_roles: ['Civil Engineer', 'Assistant Engineer'],
    relevant_departments: ['CPWD', 'State Public Works Department (PWD)', 'NHAI'],
    relevant_assignments: ['Urban Infrastructure & Roadways', 'Bridge & Highway Construction'],
    min_recommended_score: 20,
    difficulty_level: 'Beginner',
    prerequisites: [],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'National Building Code (NBC) safety regulations, trench excavation shoring, working at heights, PPE enforcement, and environmental clearance mitigations.',
    expected_outcome: 'Implement site safety checklists, prevent excavation collapses, and conduct mandatory environmental compliance reporting.'
  },

  // =========================================================================
  // 3. HEALTH & FAMILY WELFARE (Medical Officer: IDs 201..204)
  // =========================================================================
  {
    id: 201,
    title: 'Digital Health Systems & Ayushman Bharat Digital Mission (ABDM)',
    source: 'iGOT',
    competency: 'Digital Health Systems',
    secondary_competencies: ['Health Data Management', 'Clinical Governance', 'ABDM Standards'],
    target_roles: ['Medical Officer', 'Public Health Officer'],
    relevant_departments: ['Ministry of Health & Family Welfare', 'State Directorate of Health Services', 'National Health Mission (NHM)'],
    relevant_assignments: ['Digital Health Records & Ayushman Bharat', 'Hospital Clinical Governance & Quality'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Basic Clinical Administration'],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Ayushman Bharat Health Account (ABHA) creation, electronic health record (EHR) integration, consent management architectures, and tele-consultation protocols.',
    expected_outcome: 'Administer ABDM-compliant digital facility workflows, oversee seamless ABHA linkages, and ensure patient data privacy under Indian healthcare guidelines.'
  },
  {
    id: 202,
    title: 'Public Health Programme Management & National Health Mission',
    source: 'iGOT',
    competency: 'Health Programme Management',
    secondary_competencies: ['Public Health', 'Resource Planning', 'Untied Grants'],
    target_roles: ['Medical Officer', 'Public Health Officer'],
    relevant_departments: ['National Health Mission (NHM)', 'State Directorate of Health Services', 'District Health Administration'],
    relevant_assignments: ['Public Health Programme & Immunization', 'Maternal & Child Health Monitoring'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Medical Degree (MBBS) / Induction'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'National Health Mission guidelines, Program Implementation Plan (PIP) execution, RMNCH+A strategy, untied fund administration, and community stakeholder mobilization.',
    expected_outcome: 'Coordinate Primary Health Centre outreach sessions, manage Rogi Kalyan Samiti approvals, and maximize institutional delivery coverage.'
  },
  {
    id: 203,
    title: 'Clinical Governance & Quality Standards in Healthcare',
    source: 'NSSTA',
    competency: 'Clinical Governance',
    secondary_competencies: ['Public Health', 'Biomedical Waste', 'IPHS Standards'],
    target_roles: ['Medical Officer'],
    relevant_departments: ['State Directorate of Health Services', 'District Health Administration'],
    relevant_assignments: ['Hospital Clinical Governance & Quality', 'Public Health Programme & Immunization'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Hospital Administration Basics'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Indian Public Health Standards (IPHS), Biomedical Waste Management Rules 2016, infection control in secondary care facilities, prescription audit, and patient safety protocols.',
    expected_outcome: 'Audit hospital waste segregation against statutory yellow/red bins and implement antibiotic stewardship and infection prevention guidelines.'
  },
  {
    id: 204,
    title: 'Health Data Analytics & Disease Surveillance (IHIP)',
    source: 'iGOT',
    competency: 'Health Data Management',
    secondary_competencies: ['Public Health', 'Epidemiology', 'Disease Surveillance'],
    target_roles: ['Medical Officer', 'Public Health Officer'],
    relevant_departments: ['National Health Mission (NHM)', 'State Directorate of Health Services'],
    relevant_assignments: ['Disease Surveillance & Outbreak Response', 'Public Health Programme & Immunization'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Basic Epidemiology'],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Integrated Health Information Platform (IHIP) real-time syndromic and lab reporting, epidemic curve interpretation, outbreak investigation protocols, and HMIS indicators.',
    expected_outcome: 'Log real-time outbreak signals into IHIP, formulate targeted containment strategies for water-borne/vector-borne clusters, and analyze district morbidity trends.'
  },

  // =========================================================================
  // 4. FINANCE & ACCOUNTS (Finance Officer: IDs 301..305)
  // =========================================================================
  {
    id: 301,
    title: 'Financial Analytics & Data-Driven Audit in Government',
    source: 'iGOT',
    competency: 'Financial Analytics',
    secondary_competencies: ['Audit', 'Government Accounting', 'PFMS'],
    target_roles: ['Finance & Accounts Officer', 'Audit Officer'],
    relevant_departments: ['Ministry of Finance (Department of Expenditure)', 'Office of Controller General of Accounts (CGA)'],
    relevant_assignments: ['Statutory & Internal Audit Review', 'Government Budget & Accounts Scrutiny'],
    min_recommended_score: 40,
    difficulty_level: 'Intermediate',
    prerequisites: ['Government Accounting Foundations'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Automated expenditure anomaly detection in treasury databases, Benford Law analysis for procurement fraud screening, and data-driven public finance auditing.',
    expected_outcome: 'Execute automated scripts to flag unverified voucher clusters and detect scheme fund parking across subsidiary accounts.'
  },
  {
    id: 302,
    title: 'Public Financial Management System (PFMS) & General Financial Rules (GFR)',
    source: 'iGOT',
    competency: 'Public Financial Management',
    secondary_competencies: ['Financial Rules', 'Treasury Operations', 'PFMS'],
    target_roles: ['Finance & Accounts Officer', 'Accounts Officer'],
    relevant_departments: ['Ministry of Finance', 'CGA', 'State Treasury & Accounts Directorate'],
    relevant_assignments: ['Public Financial Management System (PFMS) Administration', 'Government Budget & Accounts Scrutiny'],
    min_recommended_score: 20,
    difficulty_level: 'Intermediate',
    prerequisites: ['Basic Government Accounting'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Comprehensive operational training on PFMS portals, Single Nodal Agency (SNA) models, Direct Benefit Transfer (DBT) reconciliation, and General Financial Rules (GFR) 2017.',
    expected_outcome: 'Manage SNA fund limits, resolve treasury billing rejections, and enforce Just-in-Time grants release mechanisms without fiscal slippage.'
  },
  {
    id: 303,
    title: 'Government Budgeting, Appropriation & Expenditure Control',
    source: 'NSSTA',
    competency: 'Budgeting',
    secondary_competencies: ['Public Financial Management', 'Parliamentary Financial Scrutiny'],
    target_roles: ['Finance & Accounts Officer', 'Senior Accounts Officer'],
    relevant_departments: ['Ministry of Finance (Department of Expenditure)', 'Internal Finance Wings of Ministries'],
    relevant_assignments: ['Government Budget & Accounts Scrutiny', 'Public Financial Management System (PFMS) Administration'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['GFR 2017 Overview'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Budget Estimates (BE), Revised Estimates (RE), parliamentary Vote on Account, re-appropriation limitations under GFR, and monthly expenditure ceilings.',
    expected_outcome: 'Compile ministry budget proposals, scrutinize scheme head expenditures, and ensure non-violation of voted vs charged constitutional appropriations.'
  },
  {
    id: 304,
    title: 'Government Accounting & GeM Procurement Rules',
    source: 'NSSTA',
    competency: 'Government Accounting',
    secondary_competencies: ['Financial Rules', 'Procurement', 'GFR 2017'],
    target_roles: ['Finance & Accounts Officer', 'Accounts Officer'],
    relevant_departments: ['Office of Controller General of Accounts (CGA)', 'State Treasury & Accounts Directorate'],
    relevant_assignments: ['GeM Procurement & Expenditure Control', 'Revenue Reconciliation & Treasury Operations'],
    min_recommended_score: 25,
    difficulty_level: 'Intermediate',
    prerequisites: ['Double Entry & Civil Accounts Basics'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Treasury suspense account clearance, RBI settlement reconciliations, Civil Accounts compilation, and scrutiny of GeM bills under GFR Rule 149.',
    expected_outcome: 'Clear long-pending suspense balances, audit electronic GeM sanction orders, and compile monthly classified expenditure statements.'
  },
  {
    id: 305,
    title: 'Statutory Audit & Public Accounts Scrutiny',
    source: 'iGOT',
    competency: 'Audit',
    secondary_competencies: ['Financial Rules', 'C&AG Norms', 'Public Financial Management'],
    target_roles: ['Finance & Accounts Officer', 'Audit Officer'],
    relevant_departments: ['Ministry of Finance', 'Internal Finance Wings'],
    relevant_assignments: ['Statutory & Internal Audit Review', 'Government Budget & Accounts Scrutiny'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['GFR 2017 & Treasury Rules'],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'C&AG audit compliance, answering Public Accounts Committee (PAC) queries, propriety audit scrutiny, and internal control effectiveness assessment.',
    expected_outcome: 'Draft robust audit compliance replies, identify procedural financial irregularities early, and establish internal risk mitigation matrices.'
  },

  // =========================================================================
  // 5. INFORMATION TECHNOLOGY & DIGITAL GOVERNANCE (IT Officer: IDs 401..405)
  // =========================================================================
  {
    id: 401,
    title: 'DevSecOps & Zero-Trust Architecture in Government IT',
    source: 'iGOT',
    competency: 'Cloud Security & DevSecOps',
    secondary_competencies: ['Cybersecurity', 'Cloud', 'Zero Trust'],
    target_roles: ['Information Technology Officer', 'Software Engineer', 'Cybersecurity Officer'],
    relevant_departments: ['National Informatics Centre (NIC)', 'Ministry of Electronics and Information Technology (MeitY)'],
    relevant_assignments: ['Application Security & Vulnerability Management', 'Government Cloud Infrastructure & MeghRaj'],
    min_recommended_score: 50,
    difficulty_level: 'Advanced',
    prerequisites: ['Cybersecurity Foundations', 'Cloud Architecture'],
    estimated_duration: '5 weeks (hybrid)',
    learning_type: 'Course',
    description: 'Implementing automated security scanners (SAST/DAST) in CI/CD pipelines, container runtime defense, and zero-trust identity verification for public services.',
    expected_outcome: 'Deploy zero-trust microservice policies, integrate security gating into Git pipelines, and automate container vulnerability scans.'
  },
  {
    id: 402,
    title: 'Government Application Security & Vulnerability Management',
    source: 'NSSTA',
    competency: 'Cybersecurity',
    secondary_competencies: ['Software Engineering', 'CERT-In Standards', 'STQC Audits'],
    target_roles: ['Information Technology Officer', 'Cybersecurity Officer'],
    relevant_departments: ['NIC', 'MeitY', 'Digital India Corporation'],
    relevant_assignments: ['Application Security & Vulnerability Management', 'e-Governance Portal Development & APIs'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['Web Application Fundamentals'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'OWASP Top 10 vulnerabilities in public portals, CERT-In mandatory security guidelines, STQC code audits, SSL/TLS hardening, and incident triage.',
    expected_outcome: 'Perform vulnerability assessments, patch SQL injection/cross-site scripting flaws, and obtain STQC security compliance clearance.'
  },
  {
    id: 403,
    title: 'Cloud Architecture & MeghRaj Adoption for Public Services',
    source: 'iGOT',
    competency: 'Cloud',
    secondary_competencies: ['Software Engineering', 'High Availability', 'Disaster Recovery'],
    target_roles: ['Information Technology Officer', 'Database / Cloud Administrator'],
    relevant_departments: ['NIC', 'Digital India Corporation'],
    relevant_assignments: ['Government Cloud Infrastructure & MeghRaj', 'Citizen Service Delivery Platform Operations'],
    min_recommended_score: 25,
    difficulty_level: 'Intermediate',
    prerequisites: ['Operating Systems & Networking'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'MeghRaj Government Cloud provisioning, Kubernetes container orchestration, multi-zone high availability, and Disaster Recovery (RPO/RTO) configuration.',
    expected_outcome: 'Architect resilient multi-tenant cloud hosting, configure auto-scaling groups for surge traffic, and verify automated failover drills.'
  },
  {
    id: 404,
    title: 'Secure Software Development & API Standards for e-Governance',
    source: 'iGOT',
    competency: 'Software Engineering',
    secondary_competencies: ['Digital Governance', 'REST APIs', 'IndEA Standards'],
    target_roles: ['Information Technology Officer', 'Software Engineer'],
    relevant_departments: ['NIC', 'Digital India Corporation', 'State IT Departments'],
    relevant_assignments: ['e-Governance Portal Development & APIs', 'Citizen Service Delivery Platform Operations'],
    min_recommended_score: 25,
    difficulty_level: 'Intermediate',
    prerequisites: ['Programming & Web Development'],
    estimated_duration: '4 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Clean coding practices, India Enterprise Architecture (IndEA 2.0) API guidelines, DigiLocker / Aadhaar API integrations, and OAuth 2.0 PKCE authentication.',
    expected_outcome: 'Build secure, scalable microservices consuming national digital public goods and compliant with open API standards.'
  },
  {
    id: 405,
    title: 'Data Engineering for National Registries & High-Volume Systems',
    source: 'NSSTA',
    competency: 'Data Engineering',
    secondary_competencies: ['Database Scrutiny', 'Relational Databases', 'ETL'],
    target_roles: ['Information Technology Officer', 'Database / Cloud Administrator'],
    relevant_departments: ['NIC', 'Data Storage & Dissemination Division'],
    relevant_assignments: ['National Registry Database Administration', 'Citizen Service Delivery Platform Operations'],
    min_recommended_score: 30,
    difficulty_level: 'Advanced',
    prerequisites: ['SQL & Relational Database Management'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Relational database indexing at scale (PostgreSQL/Oracle), partitioning, query execution plan tuning, ETL pipelines, and data consistency safeguards.',
    expected_outcome: 'Optimize database indexes for sub-second query performance on multi-million citizen records and build automated data pipelines.'
  },

  // =========================================================================
  // 6. PUBLIC ADMINISTRATION & GENERAL SERVICES (IDs 501..504)
  // =========================================================================
  {
    id: 501,
    title: 'Digital Workflow Automation & Smart Governance',
    source: 'iGOT',
    competency: 'Digital Workflow Automation',
    secondary_competencies: ['Public Administration', 'Office Procedures', 'e-Office'],
    target_roles: ['Administrative Officer', 'General Cadre Officer', 'Section Officer'],
    relevant_departments: ['Department of Personnel & Training (DoPT)', 'Secretariat Administration Department'],
    relevant_assignments: ['Office Workflow & e-Office Administration', 'Citizen Grievance Redressal (CPGRAMS)'],
    min_recommended_score: 30,
    difficulty_level: 'Intermediate',
    prerequisites: ['e-Office Basics'],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Streamlining ministerial workflows, smart file routing rules, digital citizen interface integration, and automated turnaround tracking.',
    expected_outcome: 'Design streamlined digital workflow blueprints that cut processing steps and eliminate bureaucratic bottlenecks.'
  },
  {
    id: 502,
    title: 'Public Administration & Office Procedure (CSMOP)',
    source: 'NSSTA',
    competency: 'Public Administration',
    secondary_competencies: ['Office Procedures', 'CSMOP', 'Official Notings'],
    target_roles: ['Administrative Officer', 'General Cadre Officer', 'Section Officer'],
    relevant_departments: ['DoPT', 'Ministry of Home Affairs', 'Secretariat Administration'],
    relevant_assignments: ['Office Workflow & e-Office Administration', 'Establishment & Service Rules Administration'],
    min_recommended_score: 15,
    difficulty_level: 'Intermediate',
    prerequisites: ['Government Service Induction'],
    estimated_duration: '2 weeks residential',
    learning_type: 'Training Programme',
    description: 'Central Secretariat Manual of Office Procedure (CSMOP), official notings, file docketing, cabinet note preparation, and administrative ethics.',
    expected_outcome: 'Draft succinct, actionable file notes citing relevant precedents, prepare cabinet summaries, and maintain official correspondence records.'
  },
  {
    id: 503,
    title: 'Government e-Marketplace (GeM) Procurement & Public Contracts',
    source: 'iGOT',
    competency: 'Procurement',
    secondary_competencies: ['Financial Rules', 'Public Administration', 'GFR 2017'],
    target_roles: ['Administrative Officer', 'General Cadre Officer', 'Finance & Accounts Officer'],
    relevant_departments: ['Secretariat Administration', 'DoPT', 'District Administration'],
    relevant_assignments: ['Public Procurement & GeM Contracting', 'General Operations & Public Service'],
    min_recommended_score: 20,
    difficulty_level: 'Beginner',
    prerequisites: [],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Procuring goods and services on GeM, drafting neutral technical bids, managing reverse auctions, and executing contract payments under GFR Rule 149.',
    expected_outcome: 'Navigate the GeM buyer portal, execute direct purchases and custom bids with zero procedural audit objections.'
  },
  {
    id: 504,
    title: 'Citizen-Centric Governance & Grievance Redressal (CPGRAMS)',
    source: 'iGOT',
    competency: 'Citizen Service',
    secondary_competencies: ['Public Administration', 'Sevottam', 'DARPG Guidelines'],
    target_roles: ['Administrative Officer', 'General Cadre Officer'],
    relevant_departments: ['Department of Administrative Reforms and Public Grievances (DARPG)', 'District Collectorates'],
    relevant_assignments: ['Citizen Grievance Redressal (CPGRAMS)', 'General Operations & Public Service'],
    min_recommended_score: 15,
    difficulty_level: 'Beginner',
    prerequisites: [],
    estimated_duration: '3 weeks (self-paced)',
    learning_type: 'Course',
    description: 'Sevottam model of service excellence, citizen charter compliance, CPGRAMS handling protocols, root-cause grievance analysis, and empathetic public communication.',
    expected_outcome: 'Resolve citizen grievances within DARPG 21-day timeline with high-quality speaking orders that improve public satisfaction ratings.'
  }
];
