import { CompetencyMapper } from './competencyMapper.ts';
import type { SourceReference } from '../database/models.ts';

export interface RawGeneratedQuestion {
  question: string;
  options: string[];
  correct_answer: string | number;
  explanation: string;
  competency?: string;
  difficulty?: string;
  source_reference?: SourceReference | null;
}

export interface ValidatedQuestion {
  question_text: string;
  options: string[];
  correct_option: number; // 0..3
  explanation: string;
  competency: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  source_reference: SourceReference | null;
}

export interface ValidationReport {
  isValid: boolean;
  validQuestions: ValidatedQuestion[];
  rejectedCount: number;
  reasons: string[];
}

export class QuizValidationService {
  /**
   * Deterministically validates an array of raw questions generated by LLM.
   */
  public static validateQuestions(
    rawQuestions: any[],
    targetCount: number,
    resourceCompetency?: string
  ): ValidationReport {
    const reasons: string[] = [];
    const validQuestions: ValidatedQuestion[] = [];
    const seenPrompts = new Set<string>();

    if (!Array.isArray(rawQuestions) || rawQuestions.length === 0) {
      return {
        isValid: false,
        validQuestions: [],
        rejectedCount: 0,
        reasons: ['No question list provided by generator.'],
      };
    }

    for (let i = 0; i < rawQuestions.length; i++) {
      const q = rawQuestions[i];

      // 1. Question text
      if (!q.question || typeof q.question !== 'string' || q.question.trim().length < 10) {
        reasons.push(`Question #${i + 1} has empty or excessively short prompt.`);
        continue;
      }
      const cleanPrompt = q.question.trim();
      const promptKey = cleanPrompt.toLowerCase().replace(/[^a-z0-9]/g, '');
      if (seenPrompts.has(promptKey)) {
        reasons.push(`Question #${i + 1} is a duplicate of a previous question.`);
        continue;
      }
      seenPrompts.add(promptKey);

      // 2. Options validation (must have exactly 4 options)
      if (!Array.isArray(q.options) || q.options.length !== 4) {
        reasons.push(`Question #${i + 1} does not contain exactly 4 options.`);
        continue;
      }

      const cleanOptions = q.options.map((opt: any) =>
        typeof opt === 'string' ? opt.trim() : String(opt || '').trim()
      );

      // Check for empty options
      if (cleanOptions.some((opt: string) => opt.length === 0)) {
        reasons.push(`Question #${i + 1} contains blank options.`);
        continue;
      }

      // Check for duplicate options
      const uniqueOptions = new Set(cleanOptions.map((o: string) => o.toLowerCase()));
      if (uniqueOptions.size < 4) {
        reasons.push(`Question #${i + 1} has duplicate options.`);
        continue;
      }

      // 3. Correct answer validation
      let correctIndex = -1;

      if (typeof q.correct_answer === 'number' && q.correct_answer >= 0 && q.correct_answer <= 3) {
        correctIndex = q.correct_answer;
      } else if (typeof q.correct_answer === 'string') {
        const ca = q.correct_answer.trim();
        // Check if correct_answer matches 'A', 'B', 'C', 'D' or '0', '1', '2', '3'
        if (/^[ABCD]$/i.test(ca)) {
          correctIndex = ca.toUpperCase().charCodeAt(0) - 65;
        } else if (/^[0-3]$/.test(ca)) {
          correctIndex = parseInt(ca, 10);
        } else {
          // Exact or substring match in options
          const matchIdx = cleanOptions.findIndex(
            (opt: string) => opt.toLowerCase() === ca.toLowerCase()
          );
          if (matchIdx !== -1) {
            correctIndex = matchIdx;
          }
        }
      }

      if (correctIndex < 0 || correctIndex > 3) {
        reasons.push(
          `Question #${i + 1} correct answer "${q.correct_answer}" does not match any of the 4 options.`
        );
        continue;
      }

      // 4. Explanation
      const explanation =
        typeof q.explanation === 'string' && q.explanation.trim().length > 0
          ? q.explanation.trim()
          : `Correct answer: ${cleanOptions[correctIndex]}. Supported by the official learning document.`;

      // 5. Difficulty validation
      let difficulty: 'Easy' | 'Medium' | 'Hard' = 'Medium';
      if (typeof q.difficulty === 'string') {
        const d = q.difficulty.trim().toLowerCase();
        if (d.includes('easy') || d.includes('beginner')) difficulty = 'Easy';
        else if (d.includes('hard') || d.includes('advanced')) difficulty = 'Hard';
        else difficulty = 'Medium';
      }

      // 6. Competency mapping
      const competency = CompetencyMapper.mapCompetency(
        q.competency,
        resourceCompetency,
        cleanPrompt
      );

      // 7. Source Reference validation
      let sourceRef: SourceReference | null = null;
      if (q.source_reference && typeof q.source_reference === 'object') {
        sourceRef = {
          page: q.source_reference.page || null,
          section: q.source_reference.section || null,
          excerpt: q.source_reference.excerpt ? String(q.source_reference.excerpt).slice(0, 200) : null,
        };
      }

      validQuestions.push({
        question_text: cleanPrompt,
        options: cleanOptions,
        correct_option: correctIndex,
        explanation,
        competency,
        difficulty,
        source_reference: sourceRef,
      });

      if (validQuestions.length >= targetCount) {
        break;
      }
    }

    const isValid = validQuestions.length >= Math.min(3, targetCount);

    return {
      isValid,
      validQuestions,
      rejectedCount: rawQuestions.length - validQuestions.length,
      reasons,
    };
  }
}
